export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  LOAD_POPULAR_MORE_SUCCESS: 'LOAD_POPULAR_MORE_SUCCESS',
  LOAD_POPULAR_MORE_FAIL: 'LOAD_POPULAR_MORE_FAIL',
  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  LOAD_TRENDING_MORE_SUCCESS: 'LOAD_TRENDING_MORE_SUCCESS',
  LOAD_TRENDING_MORE_FAIL: 'LOAD_TRENDING_MORE_FAIL',
};
